comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

page:
    resource: "@PageBundle/Resources/config/routing.yml"

category:
    resource: "@CategoryBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
