page:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   /

category:
    resource: "@CategoryBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
